// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playerdb.proto

package db

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerDB struct {
	Userid               *uint64  `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
	Openid               *string  `protobuf:"bytes,2,opt,name=Openid" json:"Openid,omitempty"`
	Nickname             *string  `protobuf:"bytes,3,opt,name=Nickname" json:"Nickname,omitempty"`
	AvatarUrl            *string  `protobuf:"bytes,4,opt,name=AvatarUrl" json:"AvatarUrl,omitempty"`
	Gold                 *uint32  `protobuf:"varint,5,opt,name=Gold" json:"Gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDB) Reset()         { *m = PlayerDB{} }
func (m *PlayerDB) String() string { return proto.CompactTextString(m) }
func (*PlayerDB) ProtoMessage()    {}
func (*PlayerDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cedc1683ddd9f4d6, []int{0}
}

func (m *PlayerDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDB.Unmarshal(m, b)
}
func (m *PlayerDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDB.Marshal(b, m, deterministic)
}
func (m *PlayerDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDB.Merge(m, src)
}
func (m *PlayerDB) XXX_Size() int {
	return xxx_messageInfo_PlayerDB.Size(m)
}
func (m *PlayerDB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDB.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDB proto.InternalMessageInfo

func (m *PlayerDB) GetUserid() uint64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *PlayerDB) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

func (m *PlayerDB) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *PlayerDB) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *PlayerDB) GetGold() uint32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerDB)(nil), "db.PlayerDB")
}

func init() { proto.RegisterFile("playerdb.proto", fileDescriptor_cedc1683ddd9f4d6) }

var fileDescriptor_cedc1683ddd9f4d6 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0x49, 0xac,
	0x4c, 0x2d, 0x4a, 0x49, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4a, 0x49, 0x52, 0xea,
	0x60, 0xe4, 0xe2, 0x08, 0x00, 0x0b, 0xbb, 0x38, 0x09, 0x89, 0x71, 0xb1, 0x85, 0x16, 0xa7, 0x16,
	0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x79, 0x20, 0x71, 0xff, 0x82, 0xd4,
	0xbc, 0xcc, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x48, 0x8a, 0x8b, 0xc3,
	0x2f, 0x33, 0x39, 0x3b, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x19, 0x2c, 0x03, 0xe7, 0x0b, 0xc9, 0x70,
	0x71, 0x3a, 0x96, 0x25, 0x96, 0x24, 0x16, 0x85, 0x16, 0xe5, 0x48, 0xb0, 0x80, 0x25, 0x11, 0x02,
	0x42, 0x42, 0x5c, 0x2c, 0xee, 0xf9, 0x39, 0x29, 0x12, 0xac, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x60,
	0x36, 0x20, 0x00, 0x00, 0xff, 0xff, 0x66, 0x1b, 0xc4, 0x8c, 0x9f, 0x00, 0x00, 0x00,
}
