// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2s.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2Stype int32

const (
	C2Stype_TYPE_MAIN C2Stype = 0
	C2Stype_TYPE_ROOM C2Stype = 1
)

var C2Stype_name = map[int32]string{
	0: "TYPE_MAIN",
	1: "TYPE_ROOM",
}

var C2Stype_value = map[string]int32{
	"TYPE_MAIN": 0,
	"TYPE_ROOM": 1,
}

func (x C2Stype) Enum() *C2Stype {
	p := new(C2Stype)
	*p = x
	return p
}

func (x C2Stype) String() string {
	return proto.EnumName(C2Stype_name, int32(x))
}

func (x *C2Stype) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(C2Stype_value, data, "C2Stype")
	if err != nil {
		return err
	}
	*x = C2Stype(value)
	return nil
}

func (C2Stype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{0}
}

type C2Scmd int32

const (
	C2Scmd_CMD_GOOD_GAME C2Scmd = 0
	//10001 - 20000
	C2Scmd_CMD_LOGIN_GET_OPENID_REQ C2Scmd = 10001
	C2Scmd_CMD_LOGIN_GET_OPENID_RES C2Scmd = 10002
	C2Scmd_CMD_LOGIN_GET_DATA_REQ   C2Scmd = 10003
	C2Scmd_CMD_LOGIN_GET_DATA_RES   C2Scmd = 10004
	C2Scmd_CMD_LOGIN_HEARTBEAT_REQ  C2Scmd = 10005
	C2Scmd_CMD_LOGIN_HEARTBEAT_RES  C2Scmd = 10006
	//20001 - 30000
	C2Scmd_CMD_GAME_JOINROOM_REQ                   C2Scmd = 20001
	C2Scmd_CMD_GAME_JOINROOM_RES                   C2Scmd = 20002
	C2Scmd_CMD_GAME_PLAYERJOIN_NOTIFY              C2Scmd = 20003
	C2Scmd_CMD_GAME_PLAYERJOIN_NOTIFY_PLACEHOLDER  C2Scmd = 20004
	C2Scmd_CMD_GAME_PLAYERLEAVE_NOTIFY             C2Scmd = 20005
	C2Scmd_CMD_GAME_PLAYERLEAVE_NOTIFY_PLACEHOLDER C2Scmd = 20006
	C2Scmd_CMD_GAME_ENTERGAME_NOTIFY               C2Scmd = 20007
	C2Scmd_CMD_GAME_ENTERGAME_NOTIFY_PLACEHOLDER   C2Scmd = 20008
	C2Scmd_CMD_GAME_INPUT_NOTIFY                   C2Scmd = 20009
	C2Scmd_CMD_GAME_INPUT_NOTIFY_PLACEHOLDER       C2Scmd = 20010
	C2Scmd_CMD_GAME_READY_REQ                      C2Scmd = 20011
	C2Scmd_CMD_GAME_READY_RES                      C2Scmd = 20012
	C2Scmd_CMD_GAME_STARTGAME_NOTIFY               C2Scmd = 20013
	C2Scmd_CMD_GAME_STARTGAME_NOTIFY_PLACEHOLDER   C2Scmd = 20014
	C2Scmd_CMD_GAME_INPUT_REQ                      C2Scmd = 20015
	C2Scmd_CMD_GAME_INPUT_RES                      C2Scmd = 20016
)

var C2Scmd_name = map[int32]string{
	0:     "CMD_GOOD_GAME",
	10001: "CMD_LOGIN_GET_OPENID_REQ",
	10002: "CMD_LOGIN_GET_OPENID_RES",
	10003: "CMD_LOGIN_GET_DATA_REQ",
	10004: "CMD_LOGIN_GET_DATA_RES",
	10005: "CMD_LOGIN_HEARTBEAT_REQ",
	10006: "CMD_LOGIN_HEARTBEAT_RES",
	20001: "CMD_GAME_JOINROOM_REQ",
	20002: "CMD_GAME_JOINROOM_RES",
	20003: "CMD_GAME_PLAYERJOIN_NOTIFY",
	20004: "CMD_GAME_PLAYERJOIN_NOTIFY_PLACEHOLDER",
	20005: "CMD_GAME_PLAYERLEAVE_NOTIFY",
	20006: "CMD_GAME_PLAYERLEAVE_NOTIFY_PLACEHOLDER",
	20007: "CMD_GAME_ENTERGAME_NOTIFY",
	20008: "CMD_GAME_ENTERGAME_NOTIFY_PLACEHOLDER",
	20009: "CMD_GAME_INPUT_NOTIFY",
	20010: "CMD_GAME_INPUT_NOTIFY_PLACEHOLDER",
	20011: "CMD_GAME_READY_REQ",
	20012: "CMD_GAME_READY_RES",
	20013: "CMD_GAME_STARTGAME_NOTIFY",
	20014: "CMD_GAME_STARTGAME_NOTIFY_PLACEHOLDER",
	20015: "CMD_GAME_INPUT_REQ",
	20016: "CMD_GAME_INPUT_RES",
}

var C2Scmd_value = map[string]int32{
	"CMD_GOOD_GAME":                           0,
	"CMD_LOGIN_GET_OPENID_REQ":                10001,
	"CMD_LOGIN_GET_OPENID_RES":                10002,
	"CMD_LOGIN_GET_DATA_REQ":                  10003,
	"CMD_LOGIN_GET_DATA_RES":                  10004,
	"CMD_LOGIN_HEARTBEAT_REQ":                 10005,
	"CMD_LOGIN_HEARTBEAT_RES":                 10006,
	"CMD_GAME_JOINROOM_REQ":                   20001,
	"CMD_GAME_JOINROOM_RES":                   20002,
	"CMD_GAME_PLAYERJOIN_NOTIFY":              20003,
	"CMD_GAME_PLAYERJOIN_NOTIFY_PLACEHOLDER":  20004,
	"CMD_GAME_PLAYERLEAVE_NOTIFY":             20005,
	"CMD_GAME_PLAYERLEAVE_NOTIFY_PLACEHOLDER": 20006,
	"CMD_GAME_ENTERGAME_NOTIFY":               20007,
	"CMD_GAME_ENTERGAME_NOTIFY_PLACEHOLDER":   20008,
	"CMD_GAME_INPUT_NOTIFY":                   20009,
	"CMD_GAME_INPUT_NOTIFY_PLACEHOLDER":       20010,
	"CMD_GAME_READY_REQ":                      20011,
	"CMD_GAME_READY_RES":                      20012,
	"CMD_GAME_STARTGAME_NOTIFY":               20013,
	"CMD_GAME_STARTGAME_NOTIFY_PLACEHOLDER":   20014,
	"CMD_GAME_INPUT_REQ":                      20015,
	"CMD_GAME_INPUT_RES":                      20016,
}

func (x C2Scmd) Enum() *C2Scmd {
	p := new(C2Scmd)
	*p = x
	return p
}

func (x C2Scmd) String() string {
	return proto.EnumName(C2Scmd_name, int32(x))
}

func (x *C2Scmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(C2Scmd_value, data, "C2Scmd")
	if err != nil {
		return err
	}
	*x = C2Scmd(value)
	return nil
}

func (C2Scmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{1}
}

type Playertype int32

const (
	Playertype_MAN  Playertype = 0
	Playertype_FAKE Playertype = 1
)

var Playertype_name = map[int32]string{
	0: "MAN",
	1: "FAKE",
}

var Playertype_value = map[string]int32{
	"MAN":  0,
	"FAKE": 1,
}

func (x Playertype) Enum() *Playertype {
	p := new(Playertype)
	*p = x
	return p
}

func (x Playertype) String() string {
	return proto.EnumName(Playertype_name, int32(x))
}

func (x *Playertype) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Playertype_value, data, "Playertype")
	if err != nil {
		return err
	}
	*x = Playertype(value)
	return nil
}

func (Playertype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{2}
}

type Action int32

const (
	Action_IDLE Action = 0
	Action_MOVE Action = 1
)

var Action_name = map[int32]string{
	0: "IDLE",
	1: "MOVE",
}

var Action_value = map[string]int32{
	"IDLE": 0,
	"MOVE": 1,
}

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (x *Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Action_value, data, "Action")
	if err != nil {
		return err
	}
	*x = Action(value)
	return nil
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{3}
}

// CMD_LOGIN_GET_OPENID_REQ
type GetOpenidReq struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=Code" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOpenidReq) Reset()         { *m = GetOpenidReq{} }
func (m *GetOpenidReq) String() string { return proto.CompactTextString(m) }
func (*GetOpenidReq) ProtoMessage()    {}
func (*GetOpenidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{0}
}

func (m *GetOpenidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOpenidReq.Unmarshal(m, b)
}
func (m *GetOpenidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOpenidReq.Marshal(b, m, deterministic)
}
func (m *GetOpenidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOpenidReq.Merge(m, src)
}
func (m *GetOpenidReq) XXX_Size() int {
	return xxx_messageInfo_GetOpenidReq.Size(m)
}
func (m *GetOpenidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOpenidReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOpenidReq proto.InternalMessageInfo

func (m *GetOpenidReq) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

// CMD_LOGIN_GET_OPENID_RES
type GetOpenidRes struct {
	Openid               *string  `protobuf:"bytes,1,opt,name=Openid" json:"Openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOpenidRes) Reset()         { *m = GetOpenidRes{} }
func (m *GetOpenidRes) String() string { return proto.CompactTextString(m) }
func (*GetOpenidRes) ProtoMessage()    {}
func (*GetOpenidRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{1}
}

func (m *GetOpenidRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOpenidRes.Unmarshal(m, b)
}
func (m *GetOpenidRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOpenidRes.Marshal(b, m, deterministic)
}
func (m *GetOpenidRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOpenidRes.Merge(m, src)
}
func (m *GetOpenidRes) XXX_Size() int {
	return xxx_messageInfo_GetOpenidRes.Size(m)
}
func (m *GetOpenidRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOpenidRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetOpenidRes proto.InternalMessageInfo

func (m *GetOpenidRes) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

// CMD_LOGIN_GET_DATA_REQ
type GetDataReq struct {
	Openid               *string  `protobuf:"bytes,1,opt,name=Openid" json:"Openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataReq) Reset()         { *m = GetDataReq{} }
func (m *GetDataReq) String() string { return proto.CompactTextString(m) }
func (*GetDataReq) ProtoMessage()    {}
func (*GetDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{2}
}

func (m *GetDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReq.Unmarshal(m, b)
}
func (m *GetDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReq.Marshal(b, m, deterministic)
}
func (m *GetDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReq.Merge(m, src)
}
func (m *GetDataReq) XXX_Size() int {
	return xxx_messageInfo_GetDataReq.Size(m)
}
func (m *GetDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReq proto.InternalMessageInfo

func (m *GetDataReq) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

// CMD_LOGIN_GET_DATA_RES
type GetDataRes struct {
	Player               *C2SPlayer `protobuf:"bytes,1,opt,name=Player" json:"Player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetDataRes) Reset()         { *m = GetDataRes{} }
func (m *GetDataRes) String() string { return proto.CompactTextString(m) }
func (*GetDataRes) ProtoMessage()    {}
func (*GetDataRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{3}
}

func (m *GetDataRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRes.Unmarshal(m, b)
}
func (m *GetDataRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRes.Marshal(b, m, deterministic)
}
func (m *GetDataRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRes.Merge(m, src)
}
func (m *GetDataRes) XXX_Size() int {
	return xxx_messageInfo_GetDataRes.Size(m)
}
func (m *GetDataRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRes proto.InternalMessageInfo

func (m *GetDataRes) GetPlayer() *C2SPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

// CMD_LOGIN_HEARTBEAT_REQ
type HeartBeatReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{4}
}

func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (m *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(m, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

// CMD_LOGIN_HEARTBEAT_RES
type HeartBeatRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRes) Reset()         { *m = HeartBeatRes{} }
func (m *HeartBeatRes) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRes) ProtoMessage()    {}
func (*HeartBeatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{5}
}

func (m *HeartBeatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRes.Unmarshal(m, b)
}
func (m *HeartBeatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRes.Marshal(b, m, deterministic)
}
func (m *HeartBeatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRes.Merge(m, src)
}
func (m *HeartBeatRes) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRes.Size(m)
}
func (m *HeartBeatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRes.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRes proto.InternalMessageInfo

// CMD_GAME_JOINROOM_REQ
type JoinRoomReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomReq) Reset()         { *m = JoinRoomReq{} }
func (m *JoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomReq) ProtoMessage()    {}
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{6}
}

func (m *JoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomReq.Unmarshal(m, b)
}
func (m *JoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomReq.Merge(m, src)
}
func (m *JoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomReq.Size(m)
}
func (m *JoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomReq proto.InternalMessageInfo

// CMD_GAME_JOINROOM_RES
type JoinRoomRes struct {
	Roomid               *uint32  `protobuf:"varint,1,req,name=Roomid" json:"Roomid,omitempty"`
	Playerid             *uint32  `protobuf:"varint,2,req,name=Playerid" json:"Playerid,omitempty"`
	Seed                 *uint32  `protobuf:"varint,3,req,name=Seed" json:"Seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRes) Reset()         { *m = JoinRoomRes{} }
func (m *JoinRoomRes) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRes) ProtoMessage()    {}
func (*JoinRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{7}
}

func (m *JoinRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRes.Unmarshal(m, b)
}
func (m *JoinRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRes.Marshal(b, m, deterministic)
}
func (m *JoinRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRes.Merge(m, src)
}
func (m *JoinRoomRes) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRes.Size(m)
}
func (m *JoinRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRes proto.InternalMessageInfo

func (m *JoinRoomRes) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *JoinRoomRes) GetPlayerid() uint32 {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return 0
}

func (m *JoinRoomRes) GetSeed() uint32 {
	if m != nil && m.Seed != nil {
		return *m.Seed
	}
	return 0
}

// CMD_GAME_READY_REQ
type ReadyReq struct {
	Roomid               *uint32  `protobuf:"varint,1,req,name=Roomid" json:"Roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyReq) Reset()         { *m = ReadyReq{} }
func (m *ReadyReq) String() string { return proto.CompactTextString(m) }
func (*ReadyReq) ProtoMessage()    {}
func (*ReadyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{8}
}

func (m *ReadyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyReq.Unmarshal(m, b)
}
func (m *ReadyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyReq.Marshal(b, m, deterministic)
}
func (m *ReadyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyReq.Merge(m, src)
}
func (m *ReadyReq) XXX_Size() int {
	return xxx_messageInfo_ReadyReq.Size(m)
}
func (m *ReadyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyReq proto.InternalMessageInfo

func (m *ReadyReq) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

// CMD_GAME_READY_RES
type ReadyRes struct {
	Roomid               *uint32  `protobuf:"varint,1,req,name=Roomid" json:"Roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyRes) Reset()         { *m = ReadyRes{} }
func (m *ReadyRes) String() string { return proto.CompactTextString(m) }
func (*ReadyRes) ProtoMessage()    {}
func (*ReadyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{9}
}

func (m *ReadyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyRes.Unmarshal(m, b)
}
func (m *ReadyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyRes.Marshal(b, m, deterministic)
}
func (m *ReadyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyRes.Merge(m, src)
}
func (m *ReadyRes) XXX_Size() int {
	return xxx_messageInfo_ReadyRes.Size(m)
}
func (m *ReadyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyRes proto.InternalMessageInfo

func (m *ReadyRes) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

// CMD_GAME_PLAYERJOIN_NOTIFY
type PlayerJoinNotify struct {
	Playerid             *uint32     `protobuf:"varint,1,req,name=Playerid" json:"Playerid,omitempty"`
	Type                 *Playertype `protobuf:"varint,2,req,name=Type,enum=msg.Playertype" json:"Type,omitempty"`
	Nickname             *string     `protobuf:"bytes,3,req,name=Nickname" json:"Nickname,omitempty"`
	AvatarUrl            *string     `protobuf:"bytes,4,req,name=AvatarUrl" json:"AvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerJoinNotify) Reset()         { *m = PlayerJoinNotify{} }
func (m *PlayerJoinNotify) String() string { return proto.CompactTextString(m) }
func (*PlayerJoinNotify) ProtoMessage()    {}
func (*PlayerJoinNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{10}
}

func (m *PlayerJoinNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoinNotify.Unmarshal(m, b)
}
func (m *PlayerJoinNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoinNotify.Marshal(b, m, deterministic)
}
func (m *PlayerJoinNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoinNotify.Merge(m, src)
}
func (m *PlayerJoinNotify) XXX_Size() int {
	return xxx_messageInfo_PlayerJoinNotify.Size(m)
}
func (m *PlayerJoinNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoinNotify.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoinNotify proto.InternalMessageInfo

func (m *PlayerJoinNotify) GetPlayerid() uint32 {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return 0
}

func (m *PlayerJoinNotify) GetType() Playertype {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Playertype_MAN
}

func (m *PlayerJoinNotify) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *PlayerJoinNotify) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

// CMD_GAME_PLAYERLEAVE_NOTIFY
type PlayerLeaveNotify struct {
	Playerid             *uint32  `protobuf:"varint,1,opt,name=Playerid" json:"Playerid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLeaveNotify) Reset()         { *m = PlayerLeaveNotify{} }
func (m *PlayerLeaveNotify) String() string { return proto.CompactTextString(m) }
func (*PlayerLeaveNotify) ProtoMessage()    {}
func (*PlayerLeaveNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{11}
}

func (m *PlayerLeaveNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLeaveNotify.Unmarshal(m, b)
}
func (m *PlayerLeaveNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLeaveNotify.Marshal(b, m, deterministic)
}
func (m *PlayerLeaveNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLeaveNotify.Merge(m, src)
}
func (m *PlayerLeaveNotify) XXX_Size() int {
	return xxx_messageInfo_PlayerLeaveNotify.Size(m)
}
func (m *PlayerLeaveNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLeaveNotify.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLeaveNotify proto.InternalMessageInfo

func (m *PlayerLeaveNotify) GetPlayerid() uint32 {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return 0
}

// CMD_GAME_ENTERGAME_NOTIFY
type EnterGameNotify struct {
	Roomid               *uint32  `protobuf:"varint,1,req,name=Roomid" json:"Roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameNotify) Reset()         { *m = EnterGameNotify{} }
func (m *EnterGameNotify) String() string { return proto.CompactTextString(m) }
func (*EnterGameNotify) ProtoMessage()    {}
func (*EnterGameNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{12}
}

func (m *EnterGameNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameNotify.Unmarshal(m, b)
}
func (m *EnterGameNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameNotify.Marshal(b, m, deterministic)
}
func (m *EnterGameNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameNotify.Merge(m, src)
}
func (m *EnterGameNotify) XXX_Size() int {
	return xxx_messageInfo_EnterGameNotify.Size(m)
}
func (m *EnterGameNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameNotify.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameNotify proto.InternalMessageInfo

func (m *EnterGameNotify) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

type InputData struct {
	Playerid             *uint32  `protobuf:"varint,1,opt,name=Playerid" json:"Playerid,omitempty"`
	Action               *Action  `protobuf:"varint,2,opt,name=Action,enum=msg.Action" json:"Action,omitempty"`
	X                    *int32   `protobuf:"varint,3,opt,name=X" json:"X,omitempty"`
	Y                    *int32   `protobuf:"varint,4,opt,name=Y" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputData) Reset()         { *m = InputData{} }
func (m *InputData) String() string { return proto.CompactTextString(m) }
func (*InputData) ProtoMessage()    {}
func (*InputData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{13}
}

func (m *InputData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputData.Unmarshal(m, b)
}
func (m *InputData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputData.Marshal(b, m, deterministic)
}
func (m *InputData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputData.Merge(m, src)
}
func (m *InputData) XXX_Size() int {
	return xxx_messageInfo_InputData.Size(m)
}
func (m *InputData) XXX_DiscardUnknown() {
	xxx_messageInfo_InputData.DiscardUnknown(m)
}

var xxx_messageInfo_InputData proto.InternalMessageInfo

func (m *InputData) GetPlayerid() uint32 {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return 0
}

func (m *InputData) GetAction() Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return Action_IDLE
}

func (m *InputData) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *InputData) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

// CMD_GAME_INPUT_NOTIFY
type InputNotify struct {
	Step                 *int32       `protobuf:"varint,1,req,name=Step" json:"Step,omitempty"`
	InputList            []*InputData `protobuf:"bytes,2,rep,name=InputList" json:"InputList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InputNotify) Reset()         { *m = InputNotify{} }
func (m *InputNotify) String() string { return proto.CompactTextString(m) }
func (*InputNotify) ProtoMessage()    {}
func (*InputNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{14}
}

func (m *InputNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputNotify.Unmarshal(m, b)
}
func (m *InputNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputNotify.Marshal(b, m, deterministic)
}
func (m *InputNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputNotify.Merge(m, src)
}
func (m *InputNotify) XXX_Size() int {
	return xxx_messageInfo_InputNotify.Size(m)
}
func (m *InputNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_InputNotify.DiscardUnknown(m)
}

var xxx_messageInfo_InputNotify proto.InternalMessageInfo

func (m *InputNotify) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *InputNotify) GetInputList() []*InputData {
	if m != nil {
		return m.InputList
	}
	return nil
}

// CMD_GAME_STARTGAME_NOTIFY
type StartGameNotify struct {
	Time                 *uint64  `protobuf:"varint,1,opt,name=Time" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameNotify) Reset()         { *m = StartGameNotify{} }
func (m *StartGameNotify) String() string { return proto.CompactTextString(m) }
func (*StartGameNotify) ProtoMessage()    {}
func (*StartGameNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{15}
}

func (m *StartGameNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameNotify.Unmarshal(m, b)
}
func (m *StartGameNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameNotify.Marshal(b, m, deterministic)
}
func (m *StartGameNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameNotify.Merge(m, src)
}
func (m *StartGameNotify) XXX_Size() int {
	return xxx_messageInfo_StartGameNotify.Size(m)
}
func (m *StartGameNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameNotify.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameNotify proto.InternalMessageInfo

func (m *StartGameNotify) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

// CMD_GAME_INPUT_REQ
type InputReq struct {
	Roomid               *uint32    `protobuf:"varint,1,req,name=Roomid" json:"Roomid,omitempty"`
	Input                *InputData `protobuf:"bytes,2,req,name=Input" json:"Input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InputReq) Reset()         { *m = InputReq{} }
func (m *InputReq) String() string { return proto.CompactTextString(m) }
func (*InputReq) ProtoMessage()    {}
func (*InputReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{16}
}

func (m *InputReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputReq.Unmarshal(m, b)
}
func (m *InputReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputReq.Marshal(b, m, deterministic)
}
func (m *InputReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputReq.Merge(m, src)
}
func (m *InputReq) XXX_Size() int {
	return xxx_messageInfo_InputReq.Size(m)
}
func (m *InputReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InputReq.DiscardUnknown(m)
}

var xxx_messageInfo_InputReq proto.InternalMessageInfo

func (m *InputReq) GetRoomid() uint32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *InputReq) GetInput() *InputData {
	if m != nil {
		return m.Input
	}
	return nil
}

// CMD_GAME_INPUT_RES
type InputRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputRes) Reset()         { *m = InputRes{} }
func (m *InputRes) String() string { return proto.CompactTextString(m) }
func (*InputRes) ProtoMessage()    {}
func (*InputRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{17}
}

func (m *InputRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputRes.Unmarshal(m, b)
}
func (m *InputRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputRes.Marshal(b, m, deterministic)
}
func (m *InputRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputRes.Merge(m, src)
}
func (m *InputRes) XXX_Size() int {
	return xxx_messageInfo_InputRes.Size(m)
}
func (m *InputRes) XXX_DiscardUnknown() {
	xxx_messageInfo_InputRes.DiscardUnknown(m)
}

var xxx_messageInfo_InputRes proto.InternalMessageInfo

type C2SPlayer struct {
	Userid               *uint64  `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
	Nickname             *string  `protobuf:"bytes,2,opt,name=Nickname" json:"Nickname,omitempty"`
	AvatarUrl            *string  `protobuf:"bytes,3,opt,name=AvatarUrl" json:"AvatarUrl,omitempty"`
	Gold                 *uint32  `protobuf:"varint,4,opt,name=Gold" json:"Gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SPlayer) Reset()         { *m = C2SPlayer{} }
func (m *C2SPlayer) String() string { return proto.CompactTextString(m) }
func (*C2SPlayer) ProtoMessage()    {}
func (*C2SPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{18}
}

func (m *C2SPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SPlayer.Unmarshal(m, b)
}
func (m *C2SPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SPlayer.Marshal(b, m, deterministic)
}
func (m *C2SPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SPlayer.Merge(m, src)
}
func (m *C2SPlayer) XXX_Size() int {
	return xxx_messageInfo_C2SPlayer.Size(m)
}
func (m *C2SPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_C2SPlayer proto.InternalMessageInfo

func (m *C2SPlayer) GetUserid() uint64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *C2SPlayer) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *C2SPlayer) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *C2SPlayer) GetGold() uint32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

// 协议头
type C2SHead struct {
	Type                 *C2Stype `protobuf:"varint,1,req,name=Type,enum=msg.C2Stype" json:"Type,omitempty"`
	Cmd                  *C2Scmd  `protobuf:"varint,2,req,name=Cmd,enum=msg.C2Scmd" json:"Cmd,omitempty"`
	Seq                  *uint32  `protobuf:"varint,3,opt,name=Seq" json:"Seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHead) Reset()         { *m = C2SHead{} }
func (m *C2SHead) String() string { return proto.CompactTextString(m) }
func (*C2SHead) ProtoMessage()    {}
func (*C2SHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{19}
}

func (m *C2SHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHead.Unmarshal(m, b)
}
func (m *C2SHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHead.Marshal(b, m, deterministic)
}
func (m *C2SHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHead.Merge(m, src)
}
func (m *C2SHead) XXX_Size() int {
	return xxx_messageInfo_C2SHead.Size(m)
}
func (m *C2SHead) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHead.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHead proto.InternalMessageInfo

func (m *C2SHead) GetType() C2Stype {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return C2Stype_TYPE_MAIN
}

func (m *C2SHead) GetCmd() C2Scmd {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return C2Scmd_CMD_GOOD_GAME
}

func (m *C2SHead) GetSeq() uint32 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

type C2SRes struct {
	Res                  *int32   `protobuf:"varint,1,opt,name=Res" json:"Res,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,opt,name=ErrCode" json:"ErrCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SRes) Reset()         { *m = C2SRes{} }
func (m *C2SRes) String() string { return proto.CompactTextString(m) }
func (*C2SRes) ProtoMessage()    {}
func (*C2SRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{20}
}

func (m *C2SRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SRes.Unmarshal(m, b)
}
func (m *C2SRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SRes.Marshal(b, m, deterministic)
}
func (m *C2SRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SRes.Merge(m, src)
}
func (m *C2SRes) XXX_Size() int {
	return xxx_messageInfo_C2SRes.Size(m)
}
func (m *C2SRes) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SRes.DiscardUnknown(m)
}

var xxx_messageInfo_C2SRes proto.InternalMessageInfo

func (m *C2SRes) GetRes() int32 {
	if m != nil && m.Res != nil {
		return *m.Res
	}
	return 0
}

func (m *C2SRes) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

// 协议
type C2S struct {
	// head
	Head                 *C2SHead           `protobuf:"bytes,1,req,name=Head" json:"Head,omitempty"`
	Result               *C2SRes            `protobuf:"bytes,2,opt,name=Result" json:"Result,omitempty"`
	GetOpenidReq         *GetOpenidReq      `protobuf:"bytes,3,opt,name=GetOpenidReq" json:"GetOpenidReq,omitempty"`
	GetOpenidRes         *GetOpenidRes      `protobuf:"bytes,4,opt,name=GetOpenidRes" json:"GetOpenidRes,omitempty"`
	GetDataReq           *GetDataReq        `protobuf:"bytes,5,opt,name=GetDataReq" json:"GetDataReq,omitempty"`
	GetDataRes           *GetDataRes        `protobuf:"bytes,6,opt,name=GetDataRes" json:"GetDataRes,omitempty"`
	HeartBeatReq         *HeartBeatReq      `protobuf:"bytes,7,opt,name=HeartBeatReq" json:"HeartBeatReq,omitempty"`
	HeartBeatRes         *HeartBeatRes      `protobuf:"bytes,8,opt,name=HeartBeatRes" json:"HeartBeatRes,omitempty"`
	JoinRoomReq          *JoinRoomReq       `protobuf:"bytes,9,opt,name=JoinRoomReq" json:"JoinRoomReq,omitempty"`
	JoinRoomRes          *JoinRoomRes       `protobuf:"bytes,10,opt,name=JoinRoomRes" json:"JoinRoomRes,omitempty"`
	PlayerJoinNotify     *PlayerJoinNotify  `protobuf:"bytes,11,opt,name=PlayerJoinNotify" json:"PlayerJoinNotify,omitempty"`
	PlayerLeaveNotify    *PlayerLeaveNotify `protobuf:"bytes,12,opt,name=PlayerLeaveNotify" json:"PlayerLeaveNotify,omitempty"`
	EnterGameNotify      *EnterGameNotify   `protobuf:"bytes,13,opt,name=EnterGameNotify" json:"EnterGameNotify,omitempty"`
	InputNotify          *InputNotify       `protobuf:"bytes,14,opt,name=InputNotify" json:"InputNotify,omitempty"`
	ReadyReq             *ReadyReq          `protobuf:"bytes,15,opt,name=ReadyReq" json:"ReadyReq,omitempty"`
	ReadyRes             *ReadyRes          `protobuf:"bytes,16,opt,name=ReadyRes" json:"ReadyRes,omitempty"`
	StartGameNotify      *StartGameNotify   `protobuf:"bytes,17,opt,name=StartGameNotify" json:"StartGameNotify,omitempty"`
	InputReq             *InputReq          `protobuf:"bytes,18,opt,name=InputReq" json:"InputReq,omitempty"`
	InputRes             *InputRes          `protobuf:"bytes,19,opt,name=InputRes" json:"InputRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_d62ebb484b362a6d, []int{21}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetHead() *C2SHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *C2S) GetResult() *C2SRes {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *C2S) GetGetOpenidReq() *GetOpenidReq {
	if m != nil {
		return m.GetOpenidReq
	}
	return nil
}

func (m *C2S) GetGetOpenidRes() *GetOpenidRes {
	if m != nil {
		return m.GetOpenidRes
	}
	return nil
}

func (m *C2S) GetGetDataReq() *GetDataReq {
	if m != nil {
		return m.GetDataReq
	}
	return nil
}

func (m *C2S) GetGetDataRes() *GetDataRes {
	if m != nil {
		return m.GetDataRes
	}
	return nil
}

func (m *C2S) GetHeartBeatReq() *HeartBeatReq {
	if m != nil {
		return m.HeartBeatReq
	}
	return nil
}

func (m *C2S) GetHeartBeatRes() *HeartBeatRes {
	if m != nil {
		return m.HeartBeatRes
	}
	return nil
}

func (m *C2S) GetJoinRoomReq() *JoinRoomReq {
	if m != nil {
		return m.JoinRoomReq
	}
	return nil
}

func (m *C2S) GetJoinRoomRes() *JoinRoomRes {
	if m != nil {
		return m.JoinRoomRes
	}
	return nil
}

func (m *C2S) GetPlayerJoinNotify() *PlayerJoinNotify {
	if m != nil {
		return m.PlayerJoinNotify
	}
	return nil
}

func (m *C2S) GetPlayerLeaveNotify() *PlayerLeaveNotify {
	if m != nil {
		return m.PlayerLeaveNotify
	}
	return nil
}

func (m *C2S) GetEnterGameNotify() *EnterGameNotify {
	if m != nil {
		return m.EnterGameNotify
	}
	return nil
}

func (m *C2S) GetInputNotify() *InputNotify {
	if m != nil {
		return m.InputNotify
	}
	return nil
}

func (m *C2S) GetReadyReq() *ReadyReq {
	if m != nil {
		return m.ReadyReq
	}
	return nil
}

func (m *C2S) GetReadyRes() *ReadyRes {
	if m != nil {
		return m.ReadyRes
	}
	return nil
}

func (m *C2S) GetStartGameNotify() *StartGameNotify {
	if m != nil {
		return m.StartGameNotify
	}
	return nil
}

func (m *C2S) GetInputReq() *InputReq {
	if m != nil {
		return m.InputReq
	}
	return nil
}

func (m *C2S) GetInputRes() *InputRes {
	if m != nil {
		return m.InputRes
	}
	return nil
}

func init() {
	proto.RegisterEnum("msg.C2Stype", C2Stype_name, C2Stype_value)
	proto.RegisterEnum("msg.C2Scmd", C2Scmd_name, C2Scmd_value)
	proto.RegisterEnum("msg.Playertype", Playertype_name, Playertype_value)
	proto.RegisterEnum("msg.Action", Action_name, Action_value)
	proto.RegisterType((*GetOpenidReq)(nil), "msg.GetOpenidReq")
	proto.RegisterType((*GetOpenidRes)(nil), "msg.GetOpenidRes")
	proto.RegisterType((*GetDataReq)(nil), "msg.GetDataReq")
	proto.RegisterType((*GetDataRes)(nil), "msg.GetDataRes")
	proto.RegisterType((*HeartBeatReq)(nil), "msg.HeartBeatReq")
	proto.RegisterType((*HeartBeatRes)(nil), "msg.HeartBeatRes")
	proto.RegisterType((*JoinRoomReq)(nil), "msg.JoinRoomReq")
	proto.RegisterType((*JoinRoomRes)(nil), "msg.JoinRoomRes")
	proto.RegisterType((*ReadyReq)(nil), "msg.ReadyReq")
	proto.RegisterType((*ReadyRes)(nil), "msg.ReadyRes")
	proto.RegisterType((*PlayerJoinNotify)(nil), "msg.PlayerJoinNotify")
	proto.RegisterType((*PlayerLeaveNotify)(nil), "msg.PlayerLeaveNotify")
	proto.RegisterType((*EnterGameNotify)(nil), "msg.EnterGameNotify")
	proto.RegisterType((*InputData)(nil), "msg.InputData")
	proto.RegisterType((*InputNotify)(nil), "msg.InputNotify")
	proto.RegisterType((*StartGameNotify)(nil), "msg.StartGameNotify")
	proto.RegisterType((*InputReq)(nil), "msg.InputReq")
	proto.RegisterType((*InputRes)(nil), "msg.InputRes")
	proto.RegisterType((*C2SPlayer)(nil), "msg.C2SPlayer")
	proto.RegisterType((*C2SHead)(nil), "msg.C2SHead")
	proto.RegisterType((*C2SRes)(nil), "msg.C2SRes")
	proto.RegisterType((*C2S)(nil), "msg.C2S")
}

func init() { proto.RegisterFile("c2s.proto", fileDescriptor_d62ebb484b362a6d) }

var fileDescriptor_d62ebb484b362a6d = []byte{
	// 1158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0x59, 0x6f, 0xdb, 0x46,
	0x10, 0x0e, 0x75, 0x5a, 0x23, 0xcb, 0xa6, 0xb7, 0x4d, 0xba, 0xcd, 0x81, 0x28, 0xcc, 0x65, 0xbb,
	0xa9, 0x03, 0x10, 0xc9, 0x6b, 0x00, 0x46, 0x62, 0x64, 0xa5, 0x12, 0xe9, 0x2e, 0xe9, 0x20, 0x02,
	0x0a, 0x08, 0x84, 0xb5, 0x4d, 0x85, 0x5a, 0x87, 0xb5, 0x4c, 0x00, 0xff, 0x88, 0x3e, 0xf4, 0x7c,
	0xd2, 0x4b, 0xef, 0xfb, 0xf8, 0x3f, 0xfd, 0x1d, 0x7d, 0x2f, 0x76, 0x48, 0xf1, 0x92, 0xe4, 0xb7,
	0x9d, 0xf9, 0xbe, 0x99, 0xfd, 0x66, 0xb9, 0xfb, 0x49, 0x50, 0x39, 0xd1, 0xc5, 0xc1, 0x74, 0x36,
	0xf1, 0x27, 0x24, 0x3f, 0x12, 0xaf, 0x34, 0x0d, 0x36, 0x5b, 0xdc, 0xb7, 0xa7, 0x7c, 0x3c, 0x1c,
	0x30, 0x7e, 0x46, 0x08, 0x14, 0x1a, 0x93, 0x01, 0xa7, 0x4a, 0x5d, 0xd9, 0xad, 0x30, 0x5c, 0x6b,
	0xf7, 0x52, 0x1c, 0x41, 0xae, 0x40, 0x29, 0x08, 0x42, 0x56, 0x18, 0x69, 0x77, 0x00, 0x5a, 0xdc,
	0x6f, 0x7a, 0xbe, 0x27, 0x3b, 0xad, 0x63, 0x3d, 0x4a, 0xb0, 0x04, 0xb9, 0x07, 0xa5, 0xa3, 0x53,
	0xef, 0x9c, 0xcf, 0x90, 0x55, 0xd5, 0xb7, 0x0e, 0x46, 0xe2, 0xd5, 0x41, 0x43, 0x77, 0x82, 0x2c,
	0x0b, 0x51, 0x6d, 0x0b, 0x36, 0x0f, 0xb9, 0x37, 0xf3, 0x9f, 0x72, 0xcf, 0x67, 0xfc, 0x2c, 0x13,
	0x0b, 0xad, 0x06, 0xd5, 0xe7, 0x93, 0xe1, 0x98, 0x4d, 0x26, 0x23, 0x09, 0x1f, 0x27, 0x43, 0x54,
	0x2c, 0x97, 0xa8, 0x25, 0xb7, 0x5b, 0x63, 0x61, 0x44, 0xae, 0xc2, 0x46, 0xd0, 0x7f, 0x38, 0xa0,
	0x39, 0x44, 0xa2, 0x58, 0x9e, 0x84, 0xc3, 0xf9, 0x80, 0xe6, 0x31, 0x8f, 0x6b, 0x4d, 0x83, 0x0d,
	0xc6, 0xbd, 0xc1, 0x79, 0x38, 0xdf, 0xaa, 0x9e, 0x09, 0xce, 0xda, 0x7d, 0xb5, 0xcf, 0x14, 0x50,
	0x83, 0x8d, 0xa4, 0x4a, 0x6b, 0xe2, 0x0f, 0x3f, 0x3e, 0x4f, 0x89, 0x51, 0x32, 0x62, 0x6e, 0x43,
	0xc1, 0x3d, 0x9f, 0x72, 0x14, 0xb9, 0xa5, 0x6f, 0xe3, 0x21, 0x4d, 0x11, 0xf4, 0xcf, 0xa7, 0x9c,
	0x21, 0x28, 0x1b, 0x58, 0xc3, 0x93, 0x4f, 0xc7, 0xde, 0x88, 0xa3, 0xea, 0x0a, 0x8b, 0x62, 0x72,
	0x1d, 0x2a, 0xc6, 0x1b, 0xcf, 0xf7, 0x66, 0xc7, 0xb3, 0x53, 0x5a, 0x40, 0x30, 0x4e, 0x68, 0x0f,
	0x61, 0x27, 0xd8, 0xaa, 0xc3, 0xbd, 0x37, 0x7c, 0xa5, 0x1e, 0x25, 0xa9, 0x47, 0xdb, 0x83, 0x6d,
	0x73, 0xec, 0xf3, 0x59, 0xcb, 0x1b, 0x2d, 0xe8, 0xeb, 0x66, 0xfd, 0x04, 0x2a, 0xed, 0xf1, 0xf4,
	0x35, 0x7e, 0xf1, 0x8b, 0x7a, 0x92, 0xdb, 0x50, 0x32, 0x4e, 0xfc, 0xe1, 0x64, 0x4c, 0x73, 0x75,
	0x65, 0x77, 0x4b, 0xaf, 0xe2, 0x94, 0x1e, 0xa6, 0x58, 0x08, 0x91, 0x4d, 0x50, 0x5e, 0xd2, 0x7c,
	0x5d, 0xd9, 0x2d, 0x32, 0xe5, 0xa5, 0x8c, 0x7a, 0xb4, 0x10, 0x44, 0x3d, 0xcd, 0x86, 0x2a, 0xee,
	0x14, 0x0a, 0x92, 0x1f, 0xd0, 0xe7, 0x53, 0x94, 0x53, 0x64, 0xb8, 0x26, 0x0f, 0x42, 0x31, 0x9d,
	0xa1, 0xf0, 0x69, 0xae, 0x9e, 0x8f, 0x6e, 0x5c, 0x24, 0x91, 0xc5, 0x04, 0xed, 0x2e, 0x6c, 0x3b,
	0xbe, 0x37, 0xf3, 0x13, 0x53, 0x12, 0x28, 0xb8, 0xc3, 0x51, 0xf0, 0x3e, 0x0a, 0x0c, 0xd7, 0xda,
	0x21, 0x6c, 0x60, 0xcd, 0x05, 0xb7, 0x82, 0xdc, 0x81, 0x22, 0x72, 0xf0, 0x0b, 0x2e, 0x6f, 0x1a,
	0x80, 0x1a, 0x44, 0x9d, 0x84, 0x76, 0x06, 0x95, 0xe8, 0x19, 0xc8, 0xb6, 0xc7, 0x22, 0x3a, 0xb5,
	0x02, 0x0b, 0xa3, 0xd4, 0x27, 0xcf, 0xe1, 0x33, 0x5b, 0xf3, 0xc9, 0xf3, 0x08, 0xc6, 0x09, 0x39,
	0x48, 0x6b, 0x72, 0x3a, 0xc0, 0xd3, 0xab, 0x31, 0x5c, 0x6b, 0x1f, 0x41, 0xb9, 0xa1, 0x3b, 0x87,
	0xdc, 0x1b, 0x90, 0x7a, 0x78, 0xe1, 0x14, 0xbc, 0x70, 0x9b, 0x28, 0xf7, 0x44, 0x17, 0x89, 0xdb,
	0x76, 0x03, 0xf2, 0x8d, 0xd1, 0x20, 0xbc, 0x91, 0xd5, 0x05, 0xe1, 0x64, 0x34, 0x60, 0x32, 0x4f,
	0x54, 0xc8, 0x3b, 0xfc, 0x0c, 0xf7, 0xad, 0x31, 0xb9, 0xd4, 0x1e, 0x41, 0xa9, 0xa1, 0x3b, 0xf2,
	0x59, 0xa8, 0x90, 0x67, 0x5c, 0xe0, 0x28, 0x45, 0x26, 0x97, 0x84, 0x42, 0xd9, 0x9c, 0xcd, 0xd0,
	0x79, 0x72, 0x98, 0x5d, 0x84, 0xda, 0xbf, 0x65, 0xc8, 0x37, 0x74, 0x47, 0x0a, 0x92, 0xc2, 0x50,
	0x50, 0x35, 0x14, 0x14, 0x8a, 0x65, 0x88, 0xc8, 0xfb, 0xc3, 0xb8, 0x78, 0x7d, 0xea, 0x63, 0x8b,
	0x6a, 0xa8, 0x29, 0xd8, 0x92, 0x85, 0x10, 0x79, 0x9c, 0xf6, 0x3b, 0xd4, 0x57, 0xd5, 0x77, 0x90,
	0x9a, 0x04, 0x58, 0xda, 0x16, 0xd3, 0x65, 0x02, 0x4f, 0x6d, 0x45, 0x99, 0x60, 0x69, 0xa7, 0x7c,
	0x98, 0x74, 0x44, 0x5a, 0xc4, 0xa2, 0xed, 0x45, 0x51, 0x98, 0x66, 0x49, 0xd3, 0x4c, 0x16, 0x08,
	0x5a, 0x5a, 0x55, 0x20, 0x58, 0xd2, 0x3f, 0x1f, 0xa7, 0x7d, 0x91, 0x96, 0x13, 0xc2, 0x92, 0x00,
	0x4b, 0xd1, 0x32, 0x65, 0x82, 0x6e, 0xac, 0x2e, 0x13, 0xa9, 0x32, 0x41, 0xf4, 0x94, 0xcb, 0xd2,
	0x0a, 0x56, 0xa9, 0x58, 0x95, 0xc8, 0xb3, 0x24, 0x29, 0x5d, 0x23, 0x28, 0xac, 0xac, 0x11, 0x2c,
	0xe5, 0xd7, 0xc6, 0xb2, 0x3d, 0xd2, 0x2a, 0x16, 0x5e, 0xc6, 0xc2, 0x2c, 0xc8, 0x96, 0xdd, 0xb4,
	0xb9, 0xc2, 0xd2, 0xe8, 0x26, 0xf6, 0xb8, 0x92, 0xe8, 0x91, 0x40, 0xd9, 0x0a, 0x0f, 0x7c, 0xb2,
	0xe4, 0x73, 0xb4, 0x86, 0x3d, 0xde, 0xc6, 0x1e, 0x19, 0x8c, 0x2d, 0x99, 0xa2, 0x9e, 0xb2, 0x24,
	0xba, 0x95, 0x18, 0x3e, 0x91, 0x67, 0x29, 0xdf, 0xda, 0x8b, 0x7f, 0x64, 0xe8, 0x36, 0x16, 0xd4,
	0xb0, 0x60, 0x91, 0x64, 0xf1, 0x6f, 0x50, 0x4c, 0x15, 0x54, 0x5d, 0xa6, 0x0a, 0x16, 0xff, 0x14,
	0x3d, 0x59, 0xf2, 0x32, 0xba, 0x93, 0x98, 0x24, 0x83, 0xb1, 0x25, 0xe3, 0xdb, 0x8b, 0x4d, 0x8e,
	0x92, 0xc4, 0x56, 0x8b, 0x24, 0x8b, 0x3d, 0x30, 0xa6, 0x0a, 0xfa, 0xd6, 0x32, 0x55, 0x44, 0x54,
	0xb1, 0x7f, 0x1f, 0xca, 0xa1, 0xab, 0x90, 0x1a, 0x54, 0xdc, 0xde, 0x91, 0xd9, 0xef, 0x1a, 0x6d,
	0x4b, 0xbd, 0x14, 0x85, 0xcc, 0xb6, 0xbb, 0xaa, 0xb2, 0xff, 0x5f, 0x11, 0x4a, 0x81, 0xbd, 0x90,
	0x1d, 0xa8, 0x35, 0xba, 0xcd, 0x7e, 0xcb, 0xb6, 0x9b, 0xfd, 0x96, 0xd1, 0x35, 0xd5, 0x4b, 0xe4,
	0x06, 0x50, 0x99, 0xea, 0xd8, 0xad, 0xb6, 0xd5, 0x6f, 0x99, 0x6e, 0xdf, 0x3e, 0x32, 0xad, 0x76,
	0xb3, 0xcf, 0xcc, 0x0f, 0xd5, 0xcf, 0xad, 0x0b, 0x60, 0x47, 0xfd, 0xc2, 0x22, 0xd7, 0xe0, 0x4a,
	0x1a, 0x6e, 0x1a, 0xae, 0x81, 0xb5, 0x5f, 0xae, 0x07, 0x1d, 0xf5, 0x2b, 0x8b, 0x5c, 0x87, 0x77,
	0x62, 0xf0, 0xd0, 0x34, 0x98, 0xfb, 0xd4, 0x34, 0x5c, 0x2c, 0xfd, 0xfa, 0x02, 0xd4, 0x51, 0xbf,
	0x91, 0x8d, 0x2f, 0xe3, 0x18, 0x46, 0xd7, 0xec, 0x3f, 0xb7, 0xdb, 0x96, 0x1c, 0x14, 0x2b, 0xbf,
	0x9d, 0x2b, 0xeb, 0x40, 0x47, 0xfd, 0x6e, 0xae, 0x90, 0x3a, 0x5c, 0x8d, 0xc0, 0xa3, 0x8e, 0xd1,
	0x33, 0x99, 0xa4, 0xf4, 0x2d, 0xdb, 0x6d, 0x3f, 0xeb, 0xa9, 0xdf, 0xcf, 0x15, 0xf2, 0x00, 0xee,
	0xad, 0x67, 0xc8, 0x4c, 0xc3, 0x3c, 0xb4, 0x3b, 0x4d, 0x93, 0xa9, 0x3f, 0xcc, 0x15, 0x72, 0x0b,
	0xae, 0x65, 0xd8, 0x1d, 0xd3, 0x78, 0x61, 0x2e, 0x1a, 0xfe, 0x38, 0x57, 0xc8, 0xfb, 0x70, 0xff,
	0x02, 0x4a, 0xaa, 0xe3, 0x4f, 0x73, 0x85, 0xdc, 0x84, 0x77, 0x23, 0xba, 0x69, 0xb9, 0x26, 0xc3,
	0x55, 0xd8, 0xef, 0xe7, 0xb9, 0x42, 0xde, 0x83, 0xbb, 0x6b, 0x09, 0xa9, 0x6e, 0xbf, 0x64, 0x0e,
	0xa3, 0x6d, 0x1d, 0x1d, 0xbb, 0x8b, 0x4e, 0xbf, 0xce, 0x15, 0x72, 0x1f, 0x6e, 0xad, 0x04, 0x53,
	0x5d, 0x7e, 0x9b, 0x2b, 0x84, 0x02, 0x89, 0x88, 0xcc, 0x34, 0x9a, 0x3d, 0x3c, 0xec, 0xdf, 0xd7,
	0x20, 0x8e, 0xfa, 0x47, 0x66, 0x0e, 0xc7, 0x35, 0x98, 0x9b, 0x9c, 0xe3, 0xcf, 0xcc, 0x1c, 0x59,
	0x42, 0x4a, 0xc1, 0x5f, 0x99, 0x7d, 0x02, 0xa9, 0x52, 0xc1, 0xdf, 0x6b, 0x10, 0x47, 0xfd, 0x67,
	0xae, 0xec, 0xdf, 0x04, 0x88, 0xff, 0xe7, 0x91, 0x32, 0xe4, 0xbb, 0x86, 0x7c, 0x1d, 0x1b, 0x50,
	0x78, 0x66, 0x7c, 0x60, 0xaa, 0xca, 0xfe, 0x75, 0x28, 0x05, 0x7f, 0x91, 0x64, 0xae, 0xdd, 0xec,
	0x98, 0x01, 0xda, 0xb5, 0x5f, 0x98, 0xaa, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x4d,
	0x31, 0xf0, 0xef, 0x0b, 0x00, 0x00,
}
